messages:
  debugMessage: "%player% tried to use '%command%'"
  reloaded: "The plugin has reloaded."
  alreadyAdmin: "Admin mode is already enabled"
  adminModeEnabled: "Admin mode is successfully enabled"
  adminModeEnabledDebug: "%player% has enabled admin mode!"
  message:
    - ""
    - " Its the message that shown to player when can't execute command"
    - ""
settings:
  debug: false
  isWhitelist: false
  list:
    - "gamemode"
    - "give"
