messages:
  debugMessage: "%player% tried to use '%command%'"
  reloaded: "§eEklenti yeniden yüklendi."
  alreadyAdmin: "Admin modu zaten aktif."
  adminModeEnabled: "Admin modu aktifleştirildi"
  adminModeEnabledDebug: "%player% has enabled admin mode!"
  message:
    - "§m                                                                                "
    - ""
    - "                   §c§l→ Komut Engelleme ←             "
    - ""
    - "   §a→ §eYalnızca izin verilen komutları kullanabilirsiniz."
    - "   §a→ §eKomutu doğru yazdığınızdan emin olun."
    - ""
    - "§m                                                                                "
settings:
  debug: false
  isWhitelist: true
  list:
    - "help"
    - "msg"
    - "say"